package resources

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/link11/terraform-provider-link11waap/internal/client"
	"github.com/link11/terraform-provider-link11waap/internal/providerutil"
)

var (
	_ resource.Resource                = &UserResource{}
	_ resource.ResourceWithImportState = &UserResource{}
)

// UserResource implements the user resource.
type UserResource struct {
	client *client.Client
}

// UserResourceModel describes the user resource data model.
type UserResourceModel struct {
	ID          types.String `tfsdk:"id"`
	ACL         types.Int64  `tfsdk:"acl"`
	ContactName types.String `tfsdk:"contact_name"`
	Email       types.String `tfsdk:"email"`
	Mobile      types.String `tfsdk:"mobile"`
	OrgID       types.String `tfsdk:"org_id"`
	OrgName     types.String `tfsdk:"org_name"`
}

// NewUserResource creates a new user resource instance.
func NewUserResource() resource.Resource {
	return &UserResource{}
}

// Metadata returns the resource type name.
func (r *UserResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_user"
}

// Schema defines the schema for the user resource.
func (r *UserResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a User account in Link11 WAAP.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the user (generated by the API).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"acl": schema.Int64Attribute{
				Description: "Access control level (1-20).",
				Required:    true,
				Validators: []validator.Int64{
					int64validator.Between(1, 20),
				},
			},
			"contact_name": schema.StringAttribute{
				Description: "Contact name for the user.",
				Required:    true,
			},
			"email": schema.StringAttribute{
				Description: "Email address for the user.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"mobile": schema.StringAttribute{
				Description: "Mobile phone number for the user.",
				Required:    true,
			},
			"org_id": schema.StringAttribute{
				Description: "Organization ID the user belongs to.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"org_name": schema.StringAttribute{
				Description: "Organization name.",
				Computed:    true,
			},
		},
	}
}

// Configure configures the resource with the provider client.
func (r *UserResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = providerutil.ConfigureClient(req.ProviderData, &resp.Diagnostics)
}

// Create creates a new user resource.
func (r *UserResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan UserResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	userReq := &client.UserCreateRequest{
		ACL:         int(plan.ACL.ValueInt64()),
		ContactName: plan.ContactName.ValueString(),
		Email:       plan.Email.ValueString(),
		Mobile:      plan.Mobile.ValueString(),
		OrgID:       plan.OrgID.ValueString(),
	}

	id, err := r.client.CreateUser(ctx, userReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating User",
			"Could not create user: "+err.Error(),
		)
		return
	}

	plan.ID = types.StringValue(id)

	// Read back to get computed values
	user, err := r.client.GetUser(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading User",
			"Could not read user after creation: "+err.Error(),
		)
		return
	}

	plan.OrgName = types.StringValue(user.OrgName)

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Read reads the user resource.
func (r *UserResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state UserResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	user, err := r.client.GetUser(ctx, state.ID.ValueString())
	if err != nil {
		if client.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error Reading User",
			"Could not read user: "+err.Error(),
		)
		return
	}

	state.ACL = types.Int64Value(int64(user.ACL))
	state.ContactName = types.StringValue(user.ContactName)
	state.Email = types.StringValue(user.Email)
	state.Mobile = types.StringValue(user.Mobile)
	state.OrgID = types.StringValue(user.OrgID)
	state.OrgName = types.StringValue(user.OrgName)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the user resource.
func (r *UserResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan UserResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	userReq := &client.UserUpdateRequest{
		ACL:         int(plan.ACL.ValueInt64()),
		ContactName: plan.ContactName.ValueString(),
		Mobile:      plan.Mobile.ValueString(),
	}

	err := r.client.UpdateUser(ctx, plan.ID.ValueString(), userReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Updating User",
			"Could not update user: "+err.Error(),
		)
		return
	}

	// Read back to refresh computed values
	user, err := r.client.GetUser(ctx, plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading User",
			"Could not read user after update: "+err.Error(),
		)
		return
	}

	plan.OrgName = types.StringValue(user.OrgName)

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes the user resource.
func (r *UserResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state UserResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteUser(ctx, state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Deleting User",
			"Could not delete user: "+err.Error(),
		)
		return
	}
}

// ImportState imports an existing user resource.
func (r *UserResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID is just the user ID (no config_id prefix)
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
