name: Secure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-24.04
    container:
      image: semgrep/semgrep
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: semgrep scan --sarif --output=semgrep.sarif --error --severity=WARNING --severity=ERROR
        env:
          SEMGREP_RULES: >-
            p/command-injection
            p/cwe-top-25
            p/gitleaks
            p/golang
            p/gosec
            p/insecure-transport
            p/owasp-top-ten
            p/r2c-best-practices
            p/r2c-bug-scan
            p/r2c-security-audit
            p/secrets
            p/security-audit
            p/sql-injection
            p/xss
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: semgrep-results
          path: semgrep.sarif

  govulncheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-file: go.mod
